---
title: "Why couldn't it have been butterflies?"
date: 2020-11-21
---

theme: minima
title: Why couldn't it have been butterflies?
author: Roma
email: romajoshileviosa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Is it very obvious that I'm new here? I have a lot to learn an I'm not sure I can do it but I might as well try :>

# social links
twitter_username: 5uppps # DO NOT include the @ character, or else the build will fail!
github_username:  Roma637 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

